# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

on:
  push:
    branches:
      - 'feature/**'

jobs:
  versioning:
    # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - id: checkVersion
        run: echo "::set-output name=VAR1::okay"
      - name: this should not run
        if: steps.step1.outputs.VAR1 == 'Lucy'
        run: echo "This should not run"
      - name: this should run
        if: steps.step1.outputs.VAR1 == 'okay'
        run: echo "This should not run"
