# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

on:
  push:
    branches:
      - 'feature/**'

jobs:
  versioning:
    # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - run: pwd
      - run: ls -la
      - id: checkVersion
        run: source pipelineHelper.sh;calculateVersion feature || exit 1 && applyVersionChange feature && echo "::set-output name=VAR1::okay" || exit 1
      - name: this should only run if version is adjusted
        if: steps.step1.outputs.VAR1 == 'Lucy'
        run: echo "commitVersionChange feature || exit 1"
      - name: this should run if version was okay
        if: steps.step1.outputs.VAR1 == 'okay'
        run: echo "This should not run"
