# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

on:
  push:
    branches:
      - 'feature/**'

jobs:
  feature_build:
    name: Feature Pipeline
    # https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#about-contexts-and-expressions
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest

    steps:
      - run: export
      - uses: actions/checkout@v2
      - run: |
        git config --global user.name 'GitHubCI'
        git config --global user.email 'githubci@noreply.github.com'
      - run: ls -la
      - id: checkVersion
        name: Check Version
        run: |
          source .github/workflows/scripts/pipelineHelper.sh
          calculateVersion feature || exit 1
          applyVersionChange feature || exit 1
      - name: Commit Version
        if: steps.checkVersion.outputs.applyVersionChange == 'true'
        run: |
          source .github/workflows/scripts/pipelineHelper.sh
          commitVersionChange feature || exit 1
      - name: Build and Test
        if: steps.checkVersion.outputs.applyVersionChange != 'true'
        run: echo "Version was not touched. Proceeding with normal build."
